<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Poppins,sans-serif_tiny-angular_96048512421654147278911_ifr</name>
   <tag></tag>
   <elementGuidId>b433e319-ee83-45c8-ad86-25d228a6f5e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@class='tox-edit-area__iframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tiny-angular_96048512421654147278911_ifr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>dee69f8c-5aed-406e-a8d6-3b0018dd5519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tiny-angular_96048512421654147278911_ifr</value>
      <webElementGuid>07d0ebf4-239e-442a-b48e-981b87930a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6b36421c-7b39-4b5e-ad56-90c2fc6bfff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>78f6c13f-0c87-4aa8-95be-2274bab1658c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rich Text Area. Press ALT-0 for help.</value>
      <webElementGuid>42a5253e-18b0-41c3-98fd-0b6c795fc8cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tox-edit-area__iframe</value>
      <webElementGuid>5c9c9818-1f0e-491e-823e-0cbcbfb6d955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tiny-angular_96048512421654147278911_ifr&quot;)</value>
      <webElementGuid>b71d34e0-084e-4950-9a65-d03313670713</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='tiny-angular_96048512421654147278911_ifr']</value>
      <webElementGuid>3cd7342c-e39a-4ece-9a72-a5403b067e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//e-wolken-editor[@id='case-description']/editor/div/div/div[2]/div/iframe</value>
      <webElementGuid>4aaace0a-2a19-472f-a223-322b028e64bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7e47a11a-b816-46fc-8de0-7f75db0db8cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'tiny-angular_96048512421654147278911_ifr' and @title = 'Rich Text Area. Press ALT-0 for help.']</value>
      <webElementGuid>599def4a-26a0-4cb3-86fe-42bb21a4ec32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
