<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchBusinessService</name>
   <tag></tag>
   <elementGuidId>6991cb06-bf2f-4356-bfae-f2121e65c83a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//mat-icon[.='search'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
