<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WatchersIcon</name>
   <tag></tag>
   <elementGuidId>d86978ef-355d-41c6-b534-0ce8e24816cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//mat-icon[.='add_circle_outline'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
